repository:
  # Repository settings
  has_wiki: false
  has_projects: false

branches:
  - name: main
    protection:
      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts: []
      
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      
      # Restrict pushes that create files larger than 100MB
      enforce_admins: true
      
      # Prevent force pushes
      allow_force_pushes: false
      
      # Allow deletions
      allow_deletions: false
      
      # Restrict who can push to matching branches
      restrictions:
        users: []
        teams: ["admin-team"]
        apps: []