name: Bug Report
description: Report a problem with the project
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.
  - type: input
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps caused the bug?
      placeholder: "1. Go to ... 2. Click ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen?"
