name: Setup Branch Protection
on:
  push:
    branches: [main]
    paths: ['.github/branch-protection.json']

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Branch Protection
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/main/protection" \
            -d @.github/branch-protection.json